version: "3.4"

services:

    home-dev:
        depends_on: 
            - database
        restart: on-failure
        environment:
            - ASPNETCORE_URLS=http://+:5050
            - DB_PWD=homedev
            - DB_USERNAME=homedev
            - DB_NAME=DEVICES
            - DB_SERVER=database
        ports:
            - "5050:5050"
        build:
            context: .

    database:
        image: postgres
        restart: on-failure
        container_name: home-dev-db
        environment:
            POSTGRES_USER: homedev
            POSTGRES_PASSWORD: homedev
            POSTGRES_DB: DEVICES
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4:4.18
        depends_on: 
            - database
        restart: on-failure
        container_name: homedev-db-admin
        depends_on:
            - database
        environment:
            PGADMIN_DEFAULT_EMAIL: dev@homedev.com
            PGADMIN_DEFAULT_PASSWORD: homedev
            PGADMIN_LISTEN_PORT: 80
        ports:
        - "9292:80"
